language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: "pip install -r requirements/base.txt"

env:
  - Django=1.6 DJANGO_SETTINGS_MODULE='project.settings'

script:
  - python project/manage.py test
